@BASE_URL = http://localhost:3000
@API_VERSION = /api/v1

#### === WELCOME ===
GET {{BASE_URL}}

#### === AUTHENTICATION ===
@AUTH_URL = {{BASE_URL}}{{API_VERSION}}/auth
@ACCESS_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlbGhmcGpvYXhxNjlndWV6a20yeXZqMzQiLCJlbWFpbCI6InJhdGFnaWYyMTRAYW1ldGl0YXMuY29tIiwidXNlcm5hbWUiOiJyYXRhZ2lmMjE0IiwiaWF0IjoxNzYxODQ0OTg5LCJleHAiOjE3NjE4NDU4ODl9.uOX8Uzcx5HMvGvNV7FUxo6wGeHnAPzPyCASZ6ym6gGU
@REFRESH_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlbGhmcGpvYXhxNjlndWV6a20yeXZqMzQiLCJlbWFpbCI6InJhdGFnaWYyMTRAYW1ldGl0YXMuY29tIiwidXNlcm5hbWUiOiJyYXRhZ2lmMjE0IiwiaWF0IjoxNzYxODQ0OTg5LCJleHAiOjE3NjI0NDk3ODl9.bZpHkuJnMcv7NH-O8n6a7oqK-3jRMnP_8EnGSdb7awM
POST {{AUTH_URL}}/google

### Authenticate a user with email and otp
POST {{AUTH_URL}}/email/request
Content-Type: application/json

{
  "email": "ratagif214@ametitas.com"
}

### Resend a user's otp
POST {{AUTH_URL}}/email/resend
Content-Type: application/json

{
  "email": "ratagif214@ametitas.com"
}

### verify a user's otp
POST {{AUTH_URL}}/email/verify
Content-Type: application/json

{ 
  "email": "ratagif214@ametitas.com",
  "otp": "2C242DA8"
}

### logout a user
POST {{AUTH_URL}}/logout
Content-Type: application/json

{
  "refreshToken": "{{REFRESH_TOKEN}}"
}

### refresh a user's token
POST {{AUTH_URL}}/refresh
Content-Type: application/json

{
  "refreshToken": "{{REFRESH_TOKEN}}"
}

#### === USERS ===
@USERS_URL = {{BASE_URL}}{{API_VERSION}}/users
@USER_URL = {{USERS_URL}}/me
@USER_ID = jr3bhkzdk1rt79ltb09z073c
### get a user's profile
GET {{USER_URL}}
Authorization: Bearer {{ACCESS_TOKEN}}

### Get a user by id
GET {{USERS_URL}}/{{USER_ID}}
Authorization: Bearer {{ACCESS_TOKEN}}

### Update user profile (username and/or avatar)
PATCH {{USER_URL}}
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "username": "newusername123",
  "avatar": 3
}

### Update only username
PATCH {{USER_URL}}
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "username": "cooluser456"
}

### Update only avatar (select avatar ID 1-10)
PATCH {{USER_URL}}
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "avatar": 7
}

### Delete a user (soft delete)
DELETE {{USER_URL}}
Authorization: Bearer {{ACCESS_TOKEN}}

#TODO: Add endpoints for users that want to be providers of services


#### === WALLETS ===
@WALLETS_URL = {{BASE_URL}}{{API_VERSION}}/wallets
@WALLET_URL = {{WALLETS_URL}}/me

### Get a user's wallet Information
GET {{WALLET_URL}}
Authorization: Bearer {{ACCESS_TOKEN}}

### Get wallet balance
GET {{WALLET_URL}}/balance
Authorization: Bearer {{ACCESS_TOKEN}}

### Get wallet address
GET {{WALLET_URL}}/address
Authorization: Bearer {{ACCESS_TOKEN}}

### Withdraw from wallet
POST {{WALLET_URL}}/withdraw/request

### Verify a withdrawal
POST {{WALLET_URL}}/withdraw/verify

### Resend a withdrawal OTP
POST {{WALLET_URL}}/withdraw/resend

### Export a user's wallet
POST {{WALLET_URL}}/export/request

### Verify export is from the correct user
POST {{WALLET_URL}}/export/verify

### Resend an export OTP
POST {{WALLET_URL}}/export/resend

//TODO: Admin endpoints for managing wallets



#### === Logistics (Hailing) ===
@LOGISTICS_URL = {{BASE_URL}}{{API_VERSION}}/logistics
@LOGISTICS_HAILING_URL = {{LOGISTICS_URL}}/hailing
@LOGISTICS_HAILING_REQUESTS_URL = {{LOGISTICS_HAILING_URL}}/requests
@LOGISTICS_HAILING_QUOTES_URL = {{LOGISTICS_HAILING_URL}}/quotes
@HAILING_REQUEST_ID = 123
@COMPLETION_TOKEN = sample-driver-token
@PIN_CODE = 4321
@LAT = 6.4481
@LNG = 3.3915
@COMPLETED_AT = 2024-04-30T13:45:00Z
@RIDER_COMPLETION_TOKEN = sample-rider-token
@RIDER_PIN_CODE = 9876

### Create a logistics hailing quote
POST {{LOGISTICS_HAILING_QUOTES_URL}}
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "estimatedTimeMinutes": 13,
  "distanceKm": 3.4,
  "vehicleClass": "normal",
  "extras": 0,
  "priority": false
}

### Create a logistics hailing request
POST {{LOGISTICS_HAILING_REQUESTS_URL}}
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "origin": {
    "latitude": 6.5244,
    "longitude": 3.3792
  },
  "destination": {
    "latitude": 6.4474,
    "longitude": 3.3903
  },
  "estimated_time_minutes": 25,
  "distance_km": 7.5,
  "price": 10000
}

### Accept a logistics hailing request
PATCH {{LOGISTICS_HAILING_REQUESTS_URL}}/{{HAILING_REQUEST_ID}}
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "status": "accepted"
}
// Response: return completion_token = encrypt(destLat, destLng, radius, issuedAt) to both rider and driver along status update

### Mark a logistics hailing request as arrived
PATCH {{LOGISTICS_HAILING_REQUESTS_URL}}/{{HAILING_REQUEST_ID}}
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "status": "arrived",
  "initiated_by": "driver"
}

### Mark a logistics hailing request as in progress
PATCH {{LOGISTICS_HAILING_REQUESTS_URL}}/{{HAILING_REQUEST_ID}}
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "status": "in_progress",
  "initiated_by": "driver"
}

### Cancel a logistics hailing request as the rider
PATCH {{LOGISTICS_HAILING_REQUESTS_URL}}/{{HAILING_REQUEST_ID}}
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "status": "canceled",
  "canceled_by": "rider",
  "reason": "Change of plans"
}

### Cancel a logistics hailing request as the driver
PATCH {{LOGISTICS_HAILING_REQUESTS_URL}}/{{HAILING_REQUEST_ID}}
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "status": "canceled",
  "canceled_by": "driver",
  "reason": "Vehicle issues"
}

### Mark a logistics hailing request as completed
PATCH {{LOGISTICS_HAILING_REQUESTS_URL}}/{{HAILING_REQUEST_ID}}
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "status": "completed",
  "initiated_by": "driver",
  "completion_token": "{{COMPLETION_TOKEN}}",
  "pin_code": "{{PIN_CODE}}",
   "location": {
    "latitude": {{LAT}},
    "longitude": {{LNG}}
  },
  "completed_at": "{{COMPLETED_AT}}"
}

### Mark a logistics hailing request as completed by the rider
PATCH {{LOGISTICS_HAILING_REQUESTS_URL}}/{{HAILING_REQUEST_ID}}
Authorization: Bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
  "status": "completed",
  "initiated_by": "rider",
  "completion_token": "{{COMPLETION_TOKEN}}",
  "location": {
    "latitude": {{LAT}},
    "longitude": {{LNG}}
  },
  "completed_at": "{{COMPLETED_AT}}"
}
